### ISSUE TITLE
1.9 Release Backlog

### ISSUE THREAD

**Issue by cheton** [cncjs/cncjs#139]
#### 1.9 Release
* [x] Visualizer not recognised g-code from T2Laser #236 
* [x] Security: A pendant UI can access to the CNCjs server even with an unauthorized token #234
* [x] Add an "ignoreErrors" option that allows continuing program execution on errors #233
* [x] Axes movement is not executed. Changes in widget is not saved #232
* [x] Error Code 202 Issue. Pausing during file #231
* [x] Allow CNCjs Desktop version to remember the Apps Screen position and size when CNCjs size and position are changed. #230
* [x] M06 not recognized like M6 #226
* [x] Support M0/M1 Program Pause and M2/M30 Program End #212
* [x] Grbl unit tracking #206
* [x] Axes labeled in cm in mm mode #205
* [x] Incorrect work offset setting in inch mode #204
* [x] Support for gCarvin firmware #203
* [x] Set all Axis's to Zero button on the main screen interface instead of hidden in sub menu #198
* [x] Concurrent display among multiple browsers without the need of manually refresh #195
* [x] Support homing on g2core #194
* [x] Probing widget on g2core does not set coordinate offset properly #191
* [x] "Go To" should move Z axis first/last #189 
* [x] Toggle grid line numbers #182
* [x] Making "Move To Work Zero" and "Move To Machine Zero" buttons configurable #181
* [x] Option to HALT if error is reported from machine interface #175
* [x] Marlin Support #162
* [x] Multiple webcam widgets #158
* [x] GRBL Console some ideas to improve #149
* [x] Feature Request: Webcam Rotate #148
* [x] Z-Probe not working properly #147
* [x] Spindle Coolant Unexpected UI Behaviour #142
* [x] Operating the spindle controls should send a feedhold or warning #138
* [x] Grbl ALARM:3 (Abort during cycle) at end of job #137
* [x] Feature Request / Inquiry for Perimeter Tracing prior to actual machining #136 
* [x] Feature Request: Orthographic projection in Visualizer #135
* [x] UI stopped updating in the middle of job #134
* [ ] File Management #132
* [x] Job duration clears out after job done #123
* [x] A-Axis - Navigation Buttons #122 
* [x] Manual tool change for GRBL #118
* [x] Laser widget #107
* [x] G2 arc code freeze #106 
* [x] Smoothieware support #94
* [x] Custom widget support #85
* [x] System command notifications and event trigger #84
